test_input_1:
  machine: LHC
  length: 1
  relativistic_gamma: 479.605064966
  calculate_wake: False
  comment: _test_coll_round
  f_params:
    start: 1e3
    stop: 1e13
    scan_type: 2
    sampling_exponent: 1e8
    points_per_decade: 1000
    min_refine: 1e11
    max_refine: 5e12
    n_refine: 50
    added:
  is_round: True
  yokoya_factors: 1 1 1 0 0
  layers:
    -
      distance_to_center: 2
      dc_resistivity: 5e-6
      resistivity_relaxation_time: 4.2
      re_dielectric_constant: 1
      magnetic_susceptibility: 0
      permeability_relaxation_frequency: inf
