test_x_component:
  wake: abs(x - 5000) + 3000 * 1j
  impedance: 5000 - abs(x - 5000) + 2000 * 1j
  name: Test component
  plane: x
  source_exponents: 1 0
  test_exponents: 0 1

test_y_component:
  wake: 1000 * (x % 5)
  impedance: 5000 - 1000 * (x % 5)
  plane: y
  source_exponents: 0 0
  test_exponents: 0 0

linear_x_dipolar:
  wake: x + 2 * 1j * x
  impedance: 3 x + 4 * 1j * x
  plane: x
  source_exponens: 1 0
  test_exponents: 0 0

dipolar_x_1:
  impedance: exp(-abs(x))
  wake: sqrt(2) / (pi ** 0.5 * (1 + x ** 2))
  plane: x
  source_exponents: 1 0
  test_exponents: 0 0
  name: Dipolar x-component 1