# On PR run the tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install xtrack xpart xfields nafflib
          cd ..
          git clone https://github.com/PyCOMPLETE/PyHEADTAIL.git
          cd PyHEADTAIL
          git checkout fix/longitudinal_wake
          pip install -e .
          cd ../xwakes
          pip install .[tests]
      - name: Run tests
        run: |
          cd tests
          pytest -v
